export const ADD_CLIENT = "ADD_CLIENT";
export const REMOVE_CLIENT = "REMOVE_CLIENT";
export const EDIT_CLIENT = "EDIT_CLIENT";

export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const REMOVE_ACCOUNT = "REMOVE_ACCOUNT";
export const EDIT_ACCOUNT = "EDIT_ACCOUNT";

export const DRAWER_OPEN_STATE_CHANGE = "DRAWER_OPEN_STATE_CHANGE";
