export const ADD_CLIENT = "ADD_CLIENT";
export const REMOVE_CLIENT = "REMOVE_CLIENT";
export const EDIT_CLIENT = "EDIT_CLIENT";

export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const REMOVE_ACCOUNT = "REMOVE_ACCOUNT";
export const EDIT_ACCOUNT = "EDIT_ACCOUNT";

export const CHANGE_DRAWER_OPEN_STATE = "CHANGE_DRAWER_OPEN_STATE";
export const CHANGE_DIALOG_OPEN_STATE = "CHANGE_DIALOG_OPEN_STATE";

export const CHANGE_CLIENTS_GRID_STATE = "CHANGE_CLIENTS_GRID_STATE";

export const SHOULD_UPDATE_CLIENT_ACCOUNTS_DRAWER = "SHOULD_UPDATE_CLIENT_ACCOUNTS_DRAWER";
